services:
  # HAPI FHIR JPA Server
  hapi-fhir-server:
    container_name: hapi-fhir-server
    image: "hapiproject/hapi:latest"
    restart: on-failure
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - hapi-fhir-db

  # PostgreSQL
  hapi-fhir-db:
    image: postgres
    container_name: hapi-fhir-db
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data

configs:
  hapi:
    file: ./hapi.application.yml
