POST http://localhost:8080/fhir/Patient/$validate HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType": "Patient",
  "meta": {
    "profile": [
      "https://hl7chile.cl/fhir/ig/clcore/StructureDefinition/CorePacienteCl"
    ]
  },
  "extension": [
    {
      "url": "https://hl7chile.cl/fhir/ig/clcore/StructureDefinition/IdentidadDeGenero",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "https://hl7chile.cl/fhir/ig/clcore/CodeSystem/CSIdentidaddeGenero",
            "code": "1",
            "display": "Masculino"
          }
        ]
      }
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Diaz",
      "given": [
        "John"
      ]
    },
    {
      "use": "usual",
      "given" : [
        "Juan"
      ],
      "family": "Diaz"
    }
  ]
}